### PR TITLE
Feature/thermometer

### PR DESCRIPTION
**Pull request by motleydev**
This PR merges #61 into the thermometer/progress bar feature that fetches content from Hasura (through an Airtable connector).

1. There's no animation on the progress bar as it's below the fold.
2. There's a bunch of unfortunate formatting changes that my nunjucks plugin in vscode added, hopefully this is still readble/ok?

### CODE REVIEW

**Comment by lynnandtonic** [comment]
@motleydev Hi! Thank you for this!

Should I be able to see the real value when I build the site locally? This is what I’m seeing which feels incorrect:
image

Is there a step I’m missing? Thanks!

**Comment by motleydev** [comment]
Hi @lynnandtonic - I'll dm you privately the environment variable you'll need.

**Comment by lynnandtonic** [comment]
@motleydev Got it! And looks good now. Thank you!

**Review by lynnandtonic — APPROVED** [review]

**Comment by lynnandtonic** [comment]
Thanks, @motleydev! 🎉

**Pull request merged**
